name: CI/CD

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
         - uses: actions/checkout@v4
         - uses: actions/setup-java@v4
           with:
            distribution: "temurin"
            java-version: "24"
            cache: "maven"
         - name: Run Checkstyle
           run: mvn checkstyle:check
         #- name: Run JaCoCo Test Coverage
          # run: mvn test jacoco:report
         - name: Run Integration Tests
           run: mvn verify
         - name: Run PMD Static code analysis 
           run: mvn pmd:check
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
        - run: echo "Deploying application..."